# Equilibrium in Two Dimensions

#### Written for the Paris Quantitative Economics Workshop (September 2022)
#### Author: [John Stachurski](http://johnstachurski.net/)

In [1]:
import numpy as np
import matplotlib.pyplot as plt

from scipy.optimize import newton, bisect

## The Market



We now consider a market for two related products, good 1 and good 2, with price vector $p = (p_1, p_2)$.

Supply of good $i$ at price $p$ is 

$$ q^s_i (p) = b_i \sqrt{p_i} $$

Demand of good $i$ at price $p$ is

$$ q^d_i (p) = \exp(-a_{i1} p_1) + \exp(-a_{i2} p_2) $$

Here $b_i$ and $a_{ij}$ are parameters.

The excess demand functions are

$$ e_i(p) = q^d_i(p) - q^s_i(p), \qquad i = 1, 2 $$

An equilibrium price vector $p^*$ is one where $e_i(p^*) = 0$.  

We set

$$ 
    A = \begin{pmatrix}
            a_{11} & a_{12} \\
            a_{21} & a_{22}
        \end{pmatrix}
    \qquad \text{and} \qquad
    b = \begin{pmatrix}
            b_1 \\
            b_2
        \end{pmatrix}
$$

Our default parameter values will be

In [125]:
A = ((0.9, 0.1),
     (0.1, 1.1))
default_A = np.array(A) * 10
default_b = np.ones(2)

In [126]:
def e(p, A=default_A, b=default_b):
    return np.exp(- A @ p) - b * np.sqrt(p)

In [140]:
p_vec_0 = (.5, .5)
e(p_vec_0)

array([-0.70036883, -0.70462803])

In [141]:
p_vec_1 = (.6, .6)
e(p_vec_1)

array([-0.77211792, -0.77385008])

In [144]:
p_vecs = np.empty((2, 2))
p_vecs[:, 0] = p_vec_0
p_vecs[:, 1] = p_vec_1
p_vecs

array([[0.5, 0.6],
       [0.5, 0.6]])

In [145]:
e(p_vecs)

array([[-0.70036883, -0.77211792],
       [-0.70462803, -0.77385008]])

### Exercise 1

Plot the contour lines and contour surface for $e_1$ and $e_2$.

Put $p_1$ on the horizonal axis and $p_2$ on the vertical axis.

### Solution